export type ColorStyle =
    | "base"
    | "base-weak"
    | "faint"
    | "faint-weak"
    | "accent"
    | "accent-weak"
    | "complement"
    | "complement-weak"
    | "critic"
    | "critic-weak"
    | "warning"
    | "warning-weak"
    | "success"
    | "success-weak";
